// ---Root---
game: "(" "game" name players equipment rules rendering? ")"

// ---Players---
players: "(" "players" positive_int forward_assignments? ")"
forward_assignments: "(" "set_forward" p1_assignment p2_assignment ")"
p1_assignment: "(" P1 (UP | DOWN | LEFT | RIGHT) ")"
p2_assignment: "(" P2 (UP | DOWN | LEFT | RIGHT) ")"

// ---Equipment---
equipment: "(" "equipment" board pieces regions? ")"
board: "(" "board" (board_square | board_rectangle | board_hexagon | board_hex_rectangle) ")"
?board_square: square_shape
?board_rectangle: rectangle_shape
?board_hexagon: hexagon_shape
?board_hex_rectangle: hex_rectangle_shape

// ---Pieces---
pieces: "(" "pieces" piece_definition+ ")"
piece_definition: "(" name (player_reference | BOTH) ")"
piece_reference: name

// ---Regions---
regions: "(" "regions" region_definition+ ")"
region_definition: "(" name (indices_arg | multi_mask_arg) ")"
region_reference: name

// ---Rules---
rules: "(" "rules" start_rules? play_rules end_rules ")"

// ---Start rules---
start_rules: "(" "start" start_rule+ ")"
start_rule: start_place
start_place: "(" "place" piece_reference player_reference (indices_arg | multi_mask_arg) ")"

// ---Play rules---
play_rules: "(" "play" play_phase+ ")"
play_phase: phase_once_through | phase_repeat
phase_once_through: "(" "once_through" play_mover_order play_super_mechanic ")"
phase_repeat: "(" "repeat" play_mover_order play_super_mechanic ")"
play_mover_order: "(" player_reference+ ")"

play_super_mechanic: play_mechanic force_pass?
play_mechanic: play_place | play_move
force_pass: "(" "force_pass" ")"

// ---Place rules---
play_place: "(" "place" piece_reference mover_reference? place_destination_constraint place_result_constraint? play_effects? ")"
place_destination_constraint: "(" "destination" super_mask ")"
place_result_constraint: "(" "result" super_predicate ")"

// ---Move rules---
play_move: "(" "move" move_type_definition play_effects? ")"
move_type_definition: move_type | "(" "or" move_type+ ")"
move_type: move_hop
         | move_slide
         | move_step

move_hop: "(" "hop" piece_reference direction_arg? piece_arg? hop_over_arg? capture_arg? priority_arg? ")"
move_slide: "(" "slide" piece_reference direction_arg? distance_arg? priority_arg? ")"
move_step: "(" "step" piece_reference direction_arg? priority_arg? ")"

// ---Effects---
play_effects: "(" "effects" play_super_effect+ ")"
play_super_effect: play_effect | play_conditional_effect

// TODO: allow multiple effects within a single conditional?
play_conditional_effect: play_if_effect | play_if_else_effect
play_if_effect: "(" "if" super_predicate play_effect ")"
play_if_else_effect: "(" "if" super_predicate play_effect "else" play_effect ")"

play_effect: effect_capture 
           | effect_extra_turn
           | effect_flip
           | effect_increment_score
           | effect_place
           | effect_promote
           | effect_set_score

effect_capture: "(" "capture" super_mask mover_arg? increment_score_arg? ")"
effect_extra_turn: "(" "extra_turn" mover_reference same_piece_arg? ")"
effect_flip: "(" "flip" super_mask mover_arg? ")"
effect_increment_score: "(" "increment_score" mover_reference function ")"
effect_place: "(" "place" piece_reference mover_reference (indices_arg | multi_mask_arg) ")"
effect_promote: "(" "promote" piece_reference piece_reference super_mask mover_arg? ")" // TODO: include mover arg?
effect_set_score: "(" "set_score" mover_reference function ")"

// ---Functions---
function: function_add
        | function_connected
        | function_constant
        | function_count
        | function_line
        | function_multiply
        | function_pattern
        | function_score
        | function_subtract

function_add: "(" "add" function+ ")"
function_connected: "(" "connected" piece_reference multi_mask_arg mover_arg? direction_arg? ")"
function_constant: positive_int
function_count: "(" "count" super_mask ")"
function_line: "(" "line" piece_reference positive_int orientation_arg? exact_arg? player_arg? exclude_arg? ")"
function_multiply: "(" "multiply" function+ ")"
function_pattern: "(" "pattern" piece_reference (pattern_arg | shape_arg) rotate_arg? player_arg? exclude_arg? ")"
function_score: "(" "score" mover_reference ")"
function_subtract: "(" "subtract" function function ")"

// ---End rules---
end_rules: "(" "end" end_rule+ ")"
end_rule: "(" "if" super_predicate end_rule_result ")"
?end_rule_result: result_win | result_lose | result_draw | result_by_score

// -- Result definitions --
result_win: "(" (mover_reference | BOTH) "win" ")"
result_lose: "(" (mover_reference | BOTH) "lose" ")"
result_draw: "(" "draw" ")"
result_by_score: "(" "by_score" ")"

// -- Mask definitions --
super_mask: mask | mask_like_function | super_mask_and | super_mask_or | super_mask_not
super_mask_and: "(" "and" super_mask+ ")"
super_mask_or: "(" "or" super_mask+ ")"
super_mask_not: "(" "not" super_mask ")"

mask: mask_adjacent
    | mask_captured
    | mask_center
    | mask_column
    | mask_corners
    | mask_corner_custodial
    | mask_custodial
    | mask_edge
    | mask_empty
    | mask_hopped
    | mask_occupied
    | mask_prev_move
    | mask_prev_start
    | mask_promoted
    | mask_row
    | mask_region

mask_adjacent: "(" "adjacent" super_mask direction_arg? ")"
mask_captured: "(" "captured" ")"
mask_center: "(" "center" ")"
mask_column: "(" "column" nonnegative_int ")"
mask_corners: "(" "corners" ")"
mask_corner_custodial: "(" "corner_custodial" piece_reference mover_arg? ")"
mask_custodial: "(" "custodial" piece_reference custodial_length_arg mover_arg? orientation_arg? ")"
mask_edge: "(" "edge" (edge | FORWARD | BACKWARD) ")"
mask_empty: "(" "empty" ")"
mask_hopped: "(" "hopped" ")"
// TODO: should things like "mover_reference" be replaced with a "mover_arg" to match syntax elsewhere? Probably yes...
mask_occupied: "(" "occupied" (mover_reference | player_reference)? ")"
mask_prev_move: "(" "prev_move" mover_reference ")"
mask_prev_start: "(" "prev_start" mover_reference ")"
mask_promoted: "(" "promoted" ")"
mask_row: "(" "row" nonnegative_int ")"
mask_region: "(" "region" region_reference ")"

// "Mask-like" functions are special functions that also support returning a mask. Currently this is only
// used for "line", but it might include other functions in the future
mask_like_function: function_line

// "Multi-masks" are special keywords that are manually split into multiple
// sub-masks at compile time. This is mostly useful for the "connected" function,
// which expects a list of masks to check for connections between
multi_mask: multi_mask_corners
          | multi_mask_edges
          | multi_mask_edges_no_corners

multi_mask_corners: "(" "corners" ")"
multi_mask_edges: "(" "edges" ")"
multi_mask_edges_no_corners: "(" "edgesNoCorners" ")"

// ---Predicate definitions---
super_predicate: predicate | super_predicate_and | super_predicate_or | super_predicate_not
super_predicate_and: "(" "and" super_predicate+ ")"
super_predicate_or: "(" "or" super_predicate+ ")"
super_predicate_not: "(" "not" super_predicate ")"

predicate: predicate_action_was
         | predicate_can_move_again
         | predicate_equals
         | predicate_exists
         | predicate_full_board
         | predicate_function
         | predicate_greater_equals
         | predicate_last_move_in
         | predicate_less_equals
         | predicate_mover_is
         | predicate_no_legal_actions
         | predicate_passed

predicate_action_was: "(" "action_was" mover_reference move_type_name ")"
predicate_can_move_again: "(" "can_move_again" move_type_name ")"
predicate_equals: "(" "=" function+ ")"
predicate_exists: "(" "exists" super_mask ")" // technically equivalent to (>= (count mask) 1) 
predicate_full_board: "(" "full_board" ")"
predicate_function: function // special syntax which is equivalent to "(>= function 1)"
predicate_greater_equals: "(" ">=" function function ")"
predicate_last_move_in: "(" "last_move_in" super_mask ")" // equivalent to (exists (and (prev_move mover) mask)), but more readable
predicate_less_equals: "(" "<=" function function ")"
predicate_mover_is: "(" "mover_is" player_reference ")"
predicate_no_legal_actions: "(" "no_legal_actions" ")"
predicate_passed: "(" "passed" (mover_reference | BOTH) ")"

// Additional (potentially optional) arguments for predicates
capture_arg: "capture:" boolean
custodial_length_arg: ANY | positive_int
direction_arg: "direction:" (direction | multi_direction)
distance_arg: "distance:" positive_int
exact_arg: "exact:" boolean
exclude_arg: "exclude:" multi_mask_arg
hop_over_arg: "hop_over:" (player_reference | mover_reference | BOTH)
increment_score_arg: "increment_score:" boolean
mover_arg: "mover:" (mover_reference | BOTH)
multi_mask_arg: multi_mask | super_mask | "(" super_mask+ ")"
orientation_arg: "orientation:" orientation
pattern_arg: "(" positive_int indices_arg ")" // The positive int is the "width" of the pattern and the indices are the positions within the pattern
indices_arg: "(" nonnegative_int+ ")"
player_arg: "player:" (player_reference | mover_reference)
piece_arg: "piece:" piece_reference
priority_arg: "priority:" nonnegative_int
rotate_arg: "rotate:" boolean
same_piece_arg: "same_piece:" boolean
shape_arg: shape_definition

// Shapes referring to board configurations (e.g. for the "pattern" function), distinct from piece shapes for rendering
shape_definition: hexagon_shape
                | hex_rectangle_shape
                | rectangle_shape
                | square_shape

hexagon_shape: "(" "hexagon" odd_int ")"
hex_rectangle_shape: "(" "hex_rectangle" positive_int positive_int ")"
rectangle_shape: "(" "rectangle" positive_int positive_int ")"
square_shape: "(" "square" positive_int ")"

// Optional rendering details
rendering: "(" "rendering" rendering_detail+ ")"
rendering_detail: color_assignment
                | piece_shape_assignment

color_assignment: "(" "color" player_reference color ")"
piece_shape_assignment: "(" "shape" piece_reference piece_shape ")"

// General-purpose definitions
?number: SIGNED_NUMBER
?nonnegative_int: /(0|[1-9][0-9]*)/
?positive_int: /[1-9][0-9]*/
?odd_int: /[0-9]*[13579]/
?boolean: TRUE | FALSE
?edge: TOP | BOTTOM | LEFT | RIGHT | TOP_LEFT | TOP_RIGHT | BOTTOM_LEFT | BOTTOM_RIGHT
?direction: true_direction | relative_direction
?move_type_name: HOP | SLIDE | STEP
?multi_direction: "(" direction+ ")"
?true_direction: UP | DOWN | LEFT | RIGHT | UP_LEFT | UP_RIGHT | DOWN_LEFT | DOWN_RIGHT | VERTICAL | HORIZONTAL | ORTHOGONAL | DIAGONAL | BACK_DIAGONAL | FORWARD_DIAGONAL | ANY
?relative_direction: FORWARD | BACKWARD | FORWARD_LEFT | FORWARD_RIGHT | BACKWARD_LEFT | BACKWARD_RIGHT
?orientation: VERTICAL | HORIZONTAL | ORTHOGONAL | DIAGONAL | BACK_DIAGONAL | FORWARD_DIAGONAL | ANY
?color: WHITE | BLACK
?piece_shape: CIRCLE | SQUARE | TRIANGLE | STAR | DIAMOND
// ----------------------------

?player_reference: P1 | P2
?mover_reference: MOVER | OPPONENT
?name: STRING
variable_name: /\?[a-z][a-z0-9]*/
id: /[a-zA-Z0-9_]+/

// Constants
TOP: "top"
BOTTOM: "bottom"
UP: "up"
DOWN: "down"
LEFT: "left"
RIGHT: "right"
TOP_LEFT: "top_left"
TOP_RIGHT: "top_right"
BOTTOM_LEFT: "bottom_left"
BOTTOM_RIGHT: "bottom_right"
UP_LEFT: "up_left"
UP_RIGHT: "up_right"
DOWN_LEFT: "down_left"
DOWN_RIGHT: "down_right"
VERTICAL: "vertical"
HORIZONTAL: "horizontal"
ORTHOGONAL: "orthogonal"
DIAGONAL: "diagonal"
BACK_DIAGONAL: "back_diagonal"
FORWARD_DIAGONAL: "forward_diagonal"
FORWARD: "forward"
BACKWARD: "backward"
FORWARD_LEFT: "forward_left"
FORWARD_RIGHT: "forward_right"
BACKWARD_LEFT: "backward_left"
BACKWARD_RIGHT: "backward_right"
ANY: "any"
TRUE: "true"
FALSE: "false"
MOVER: "mover"
OPPONENT: "opponent"
P1: "P1"
P2: "P2"
BOTH: "both"
HOP: "hop"
SLIDE: "slide"
STEP: "step"

WHITE: "white"
BLACK: "black"
CIRCLE: "circle"
SQUARE: "square"
TRIANGLE: "triangle"
STAR: "star"
DIAMOND: "diamond"

// Lark imports
%import common.ESCAPED_STRING -> STRING
%import common.SIGNED_NUMBER
%import common.WS
%ignore WS